GET http://localhost:3000/users/

###
POST http://localhost:3000/users/
Content-Type: application/json  

{
  "name": "Olivia",
  "age": 21,
  "email": "olivia@gmail.com",
  "password": "blabla245"
}

###
POST http://localhost:3000/users/
Content-Type: application/json  

{
  "name": "Olivia",
  "age": 21,
  "email": "olivia2@gmail.com",
  "password": "blabla245"
}

###
GET http://localhost:3000/users/67b597d55c7afac19c6d353c/

###
PUT http://localhost:3000/users/67b59f534023bc389983d61e
Content-Type: application/json

{
  "name": "Olivia Updated",
  "age": 22,
  "email": "olivia_updated@gmail.com",
  "password": "newpassword123"
}

###
DELETE http://localhost:3000/users/67b597ed5c7afac19c6d3543

### STORAGE
GET http://localhost:3000/storage/

###
POST http://localhost:3000/storage/ HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="image"; filename="mongoose_logo.png"
Content-Type: image/png

< ./mongoose_logo.png
--boundary123--

### 
GET http://localhost:3000/storage/67b5a61b1e1e904b99ff279f

###
DELETE http://localhost:3000/storage/67b59f8f97433bf9da1a0b73

###
PUT http://localhost:3000/storage/67b59f8f97433bf9da1a0b73
Content-Type: application/json

{
  "url": "new_url",
  "filename": "new_fichero"
}

###
GET http://localhost:3000/file-1740047426664.png

### 
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

###
POST http://localhost:3000/users/
Content-Type: application/json  

{
  "name": "Olivia",
  "age": 21,
  "email": "olivia3@gmail.com",
  "password": "blabla245",
  "telefono": 345346
}

###
GET http://localhost:3000/users/

### Tracks
POST http://localhost:3000/tracks/
Content-Type: application/json

{
  "name": "Track Name",
  "album": "Album Name",
  "cover": "http://example.com/cover.jpg",
  "artist": {
    "name": "Artist Name",
    "nickname": "Artist Nickname",
    "nationality": "Artist Nationality"
  },
  "duration": {
    "start": 0,
    "end": 300
  }
}

###

GET http://localhost:3000/tracks/

###

GET http://localhost:3000/auth/register

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Olivia",
  "age": 21,
  "email": "olivia@gmail.com",
  "password": "blabla245"
}

###

POST http://localhost:3000/auth/register HTTP/1.1 
Content-Type: application/json 

{
  "name": "Menganito",
  "age": 20,
  "email": "test@test.com",
  "password": "HolaMundo.01"
}

###
 
POST http://localhost:3000/auth/login HTTP/1.1 
Content-Type: application/json 

{ "email": "test@test.com", "password": "HolaMundo.01" }

###

GET http://localhost:3000/tracks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2M5ODI0NGE4NzVlZTVkYzcxMzE0MzAiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MTI1OTMzMiwiZXhwIjoxNzQxMjY2NTMyfQ.skKZhEIXU7ALmaKOLJSnqJ4Yn0oITaPKCB0U6mDOKj8